MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrained_models/e2e_faster_rcnn_R_50_C4_1x_trimmed_multipot.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 13
DATASETS:
  TRAIN: ("home_15_train_multipot",)
  TEST: ("home_15_test_multipot",)
SOLVER:
  BASE_LR: 0.0011
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 60000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 2000
OUTPUT_DIR: "training/c4_latest_multipot"

TEST:
  IMS_PER_BATCH: 1